version: '3.8'

services:
  # Сервер для отдачи статических файлов
  nginx:
    image: nginx:alpine
    container_name: elevator-app-nginx
    ports:
      - "8082:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 